### ISSUE TITLE
Gem bundle error

### ISSUE THREAD

**Issue by ghost** [algobasket/PeatioCryptoExchange#11]
Hello! 

 I am getting this error when running bundle install.

Network error while fetching https://rubygems.org/quick/Marshal.4.8/aasm-3.4.0.gemspec.rz (execution expired)

I have tried a few times and its still having the same issue.

**Comment by ghost** [comment]
Guess it had to do with IPv6, I have disabled it for now.

**Comment by algobasket** [comment]
@TheRealHotSwap check your internet connection
