### ISSUE TITLE
add new currency

### ISSUE THREAD

**Issue by cryptonana** [algobasket/PeatioCryptoExchange#12]
i see your video and demo and i open admin panel but i dont see any option to add new currency how can add new currency in exchange

**Comment by algobasket** [comment]
@cryptonana for adding new currencies you need to manually configure them.
https://github.com/algobasket/PeatioCryptoExchange/blob/rebuild-peatio/doc/Adding-New-Coin.md

**Comment by cryptonana** [comment]
ok dear thanks and tell me how can make pairs like btc/usdt btc/ltc btc/eth this time seprate tab like  BTC   ETH  USDT

and tell me whats the server requirments hardware,

can you make video for adding new coins it will be helpfull to beginners

**Comment by cryptonana** [comment]
and tell me whats the server requirments hardware, and i want live trading platform so i use  Deploy production server

**Comment by cryptonana** [comment]
can you make video for adding new coins it will be helpfull to beginners

**Comment by algobasket** [comment]
@cryptonana 
200GB Space for each Coin or Token
Sure I can make video for adding new coins
Add me on skype : algobasket

**Comment by cryptonana** [comment]
i already add you but you not on skype last seen 14 hrs ago

**Comment by knkrth** [comment]
@algobasket Can you please make a video on how to add a new coin.

**Comment by ultra-pool** [comment]
This link https://github.com/algobasket/PeatioCryptoExchange/blob/rebuild-peatio/doc/Adding-New-Coin.md Is no longer good.
