### ISSUE TITLE
Delete members

### ISSUE THREAD

**Issue by ghost** [algobasket/PeatioCryptoExchange#15]
Does anyone know how to delete members from the database?

**Comment by algobasket** [comment]
>mysql -u <USER> -p 
mysql > use peatio_production;
mysql > delete from members where email = 'YOUR EMAIL';

**Comment by algobasket** [comment]
![screenshot from 2018-11-07 11-09-18](https://user-images.githubusercontent.com/8275673/48112694-a01f5f00-e27d-11e8-812a-36c94a023748.png)

**Comment by ghost** [comment]
ok, cool thanks
I guess i could just install myphpadmin too ha

**Comment by algobasket** [comment]
@TheRealHotSwap don't use apache server, connect phpmyadmin with nginx server if you can  .But you can also run apache and nginx server both if you change the port of apache or nginx from 80 to something else . :+1:

**Comment by pankaj9310** [comment]
Run Rails_env=production rails c
M=Member.find id
M.delete
