### ISSUE TITLE
bundle exec rake db:setup error

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [algobasket/PeatioCryptoExchange#18]
thanks for the tutorial, everything was doing well until i run: **bundle exec rake db:setup** so i got the error bellow, can you help me? thanks.

> deploy@ubuntupeatio-VirtualBox:~/peatio$ bundle exec rake db:setup
> rake aborted!
> Psych::SyntaxError: (<unknown>): could not find expected ':' while scanning a simple key at line 48 column 3
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
> /home/deploy/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
> /home/deploy/peatio/config/application.rb:15:in `<module:Peatio>'
> /home/deploy/peatio/config/application.rb:14:in `<top (required)>'
> /home/deploy/peatio/Rakefile:5:in `require'
> /home/deploy/peatio/Rakefile:5:in `<top (required)>'
> /home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
> /home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
> (See full trace by running task with --trace)
>

**Comment by openbooknoobdeveloper** [comment]
space error inside the .yml files :(, fixed.

**Comment by bitbd83** [comment]
not solved
NoMethodError: undefined method `observers=' for ActiveRecord::Base:Class
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:110:in `block (3 levels) in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:109:in `each'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:109:in `block (2 levels) in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:108:in `block in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
/home/deploy/.rbenv/peatio/config/environment.rb:5:in `<top (required)>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
