### ISSUE TITLE
bundle install  errors

### ISSUE THREAD

**Issue by openbooknoobdeveloper** [algobasket/PeatioCryptoExchange#22]
I am asking myself why this errors started show up hahahah, I swear to god all runned perfect on this morning.

now 
I tried run the command: bundle install --without development test --path vendor/bundle

and I get this:

`Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.4.2
Using aasm 3.4.0
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.10.1
Installing atomic 1.1.99 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/atomic-1.1.99/.coveralls.yml
Using tzinfo 0.3.42
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using mime-types 1.25.1
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.2
Using bundler 1.11.2
Using thor 0.19.1
Using hike 1.2.3
Using tilt 1.4.1
Using amq-protocol 1.9.2
Installing eventmachine 1.0.4 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.0.4/.gitignore
Using angularjs-rails 1.3.15
Using awesome_print 1.2.0
Using descendants_tracker 0.0.3
Using ice_nine 0.11.0
Installing bcrypt-ruby 3.1.2 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/bcrypt-ruby-3.1.2/.gitignore
Using sass 3.2.19
Using browser 0.8.0
Using cancancan 1.7.1
Installing json 1.8.1 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/json-1.8.1/.gitignore
Using chronic 0.10.2
Using coderay 1.1.0
Using coffee-script-source 1.7.0
Using execjs 2.2.1
Using currencies 0.4.2
Using daemons 1.1.9
Using structured_warnings 0.1.4
Using eco-source 1.1.0.rc.1
Installing http_parser.rb 0.6.0 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/http_parser.rb-0.6.0/.gitignore
Using equalizer 0.0.9
Using multipart-post 2.0.0
Installing ffi 1.9.3 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.3/ffi.gemspec
Using formatador 0.2.5
Using request_store 1.1.0
Using hashie 3.3.2
Using multi_xml 0.5.5
Using kramdown 1.3.3
Using rb-fsevent 0.10.3
Using lumberjack 1.0.13
Using nenv 0.3.0
Using shellany 0.0.1
Using method_source 0.8.2
Using slop 3.4.7
Using guard-compat 1.2.1
Using http_accept_language 2.0.1
Using httpclient 2.3.4.1
Using jwt 2.1.0
Using mini_portile 0.6.2
Installing mysql2 0.3.21 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/mysql2-0.3.21/LICENSE
Using phonelib 0.3.5
Using signature 0.1.7
Installing rbtree 0.4.2 with native extensions

Errno::EACCES: Permission denied @ rb_sysopen - /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/rbtree-0.4.2/LICENSE
Using redis 3.0.7
Using rotp 1.6.1
Using temple 0.6.7
An error occurred while installing atomic (1.1.99), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.99'` succeeds before bundling.
`

**Comment by algobasket** [comment]
rm -rf ~/.rbenv 
then continue
