### ISSUE TITLE
site images don't load

### ISSUE THREAD

**Issue by aminaqi** [algobasket/PeatioCryptoExchange#29]
![image](https://user-images.githubusercontent.com/42599315/49036852-0852c800-f1ce-11e8-9237-6b893117d83a.png)

any solution for this?

**Comment by algobasket** [comment]
seems like route issue or may be folder permission issue 
>sudo chmod 777 -R   .  
(do it inside assets folder)

**Comment by kodcoin** [comment]
algobasket Why aren't you in contact with me?
