### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by cryptobot123** [algobasket/PeatioCryptoExchange#30]
I successfully Installed peatio in production mode , no error how ever when i run it gives me ERROR 
404 NOT FOUND ! any one can help me?

**Comment by CamXcoiN** [comment]
same here

**Comment by sp1k31973** [comment]
same here

**Comment by algobasket** [comment]
@CamXcoiN @sp1k31973 
GO to /home/deploy/peatio/config/nginx.conf  and change elementaryos to deploy
Then 
sudo rm /etc/nginx/conf.d/peatio.conf
sudo ln -s /home/deploy/peatio/config/nginx.conf /etc/nginx/conf.d/peatio.conf
sudo service nginx restart

https://github.com/algobasket/PeatioCryptoExchange/issues/13
:+1:

**Comment by zutugecof** [comment]
> @CamXcoiN @sp1k31973
> GO to /home/deploy/peatio/config/nginx.conf and change elementaryos to deploy
> Then
> sudo rm /etc/nginx/conf.d/peatio.conf
> sudo ln -s /home/deploy/peatio/config/nginx.conf /etc/nginx/conf.d/peatio.conf
> sudo service nginx restart
> 
> #13

Thanks problem solved !
