### ISSUE TITLE
errors setup

### ISSUE THREAD

**Issue by HydroxydeTech** [algobasket/PeatioCryptoExchange#34]
Installing dependency gems
./peatio-fresh-installer.sh: line 168: bundle: command not found
Prepare configure files
/usr/bin/env: ruby: No such file or directory
Setup Pusher
sed: can't read config/application.yml: No such file or directory
sed: can't read config/application.yml: No such file or directory
sed: can't read config/application.yml: No such file or directory
ENTER YOUR SSH IP OR DOMAIN NAME :  sship
185.22.232.222
sed: can't read config/application.yml: No such file or directory
USE http or https :  protocol
http
sed: can't read config/application.yml: No such file or directory
Setup bitcoind rpc endpoint
Enter Bitcoin Username:  bitcoinusername
bitcoinusername
sed: can't read config/currencies.yml: No such file or directory
Enter Bitcoin Password:  bitcoinpass
bitcoinusername
sed: can't read config/currencies.yml: No such file or directory
Config database settings
Enter MySQL Username:  mysqlusername
root
sed: can't read config/database.yml: No such file or directory
Enter MySQL Password:  mysqlpassword
qw12345
sed: can't read config/database.yml: No such file or directory
Initialize the database and load the seed data
./peatio-fresh-installer.sh: line 211: bundle: command not found
Precompile assets
./peatio-fresh-installer.sh: line 215: bundle: command not found
Running Daemons
Running Daemons
Passenger Setting
rm: cannot remove ‘/etc/nginx/sites-enabled/default’: No such file or directory
ln: failed to create symbolic link ‘/etc/nginx/conf.d/peatio.conf’: No such file or directory
nginx: unrecognized service

**Comment by algobasket** [comment]
use peatio-repair-installer.sh if your earlier installation has error Or follow this tutorial - https://www.youtube.com/c/algobasket

**Comment by HydroxydeTech** [comment]
Thank you, did everything exactly as in the video. But the site does not open - ERR_CONNECTION_REFUSED

**Comment by algobasket** [comment]
send me screenshot of it

**Comment by HydroxydeTech** [comment]
skype?discord or telegram?

**Comment by algobasket** [comment]
skype : algobasket

**Comment by HydroxydeTech** [comment]
Thanks, problem solved by algobasket
