### ISSUE TITLE
Can we install it using docker ? and all coins inside separate docker containers 

### ISSUE THREAD

**Issue by vumalebodo** [algobasket/PeatioCryptoExchange#36]
I want to know if I can install each coins daemons inside separate docker containers so I can use single vps instance running separate coin containers
Thanks in advance

**Comment by algobasket** [comment]
Yes you can install coins inside each docker container for scalability but make sure you have enough space for each full node to get install inside it .

**Comment by vumalebodo** [comment]
ok thanks

**Comment by yarepecujo** [comment]
can this be done using kubernetes for deploying on google cloud instances ?

**Comment by algobasket** [comment]
> can this be done using kubernetes for deploying on google cloud instances ?

yes you can
