### ISSUE TITLE
Nginx SITE DON'T LOAD

### ISSUE THREAD

**Issue by TTcoinDeveloper** [algobasket/PeatioCryptoExchange#37]
Can I get some help with the last part of building peatio 

![image](https://user-images.githubusercontent.com/29513200/52499709-63337300-2bb2-11e9-8b53-d61cc0d7acbe.png)

it is done but when I load the UI I get 

![image](https://user-images.githubusercontent.com/29513200/52499728-6e869e80-2bb2-11e9-9203-289b6baf4082.png)

can you help me?

**Comment by TTcoinDeveloper** [comment]
fixed

**Comment by algobasket** [comment]
Hope that fixed if you have any other issues lemme know thanks !

**Comment by TTcoinDeveloper** [comment]
Yes I do, I am trying to connect to UI externally so it should be 0.0.0.0:3000 and not localhost:3000 the ting is what file do I edit to make this change? Everytime I navigate to a page it gets directed to localhost:3000 and of course externally the page will not load..... so what do I do?

**Comment by TTcoinDeveloper** [comment]
I have added host: 0.0.0.0 to database.yml and also changed boot.rb to use 0.0.0.0 or is it nginx itself that needs configs or could it be limited in production mode please point me in the right direction here

**Comment by algobasket** [comment]
0.0.0.0:3000 is for internal server communication not for external use .For external you need to use loopback localhost or 127.0.0.1 if you're working locally not on any external vps instance .
You only need to add on application.yml and nowhere else

**Comment by algobasket** [comment]
also go to config/nginx.conf   and change elementaryOs to deploy

**Comment by TTcoinDeveloper** [comment]
I have already done this and succeeded

**Comment by TTcoinDeveloper** [comment]
The problem arises when I navigate to funds or any other page except main page

**Comment by TTcoinDeveloper** [comment]
It redirects to localhost:3000

**Comment by TTcoinDeveloper** [comment]
and fails

**Comment by algobasket** [comment]
Try to use it via Vagrant if you're installing locally

**Comment by algobasket** [comment]
Peatio Version 3 I will release soon and it will be easy for you !

**Comment by TTcoinDeveloper** [comment]
Ok I can do this

**Comment by TTcoinDeveloper** [comment]
I am planning on hosting my own coins via rpc so I would definately look forward to the new version test it out first

**Comment by pankaj9310** [comment]
@TTcoinDeveloper 
Hi change URL_HOST in application.yml file
URL_HOST: localhost:3000  to domain.com or your ip address

**Comment by Apollo-IT** [comment]
Hi, @TTcoinDeveloper  How are you?
You look like you're finding an open source cryptocurrency exchange.
I can guide you.
Please contact me.
Regards.

Skype: live:apollo447722
Email: apollo447722@outlook.com
