### ISSUE TITLE
Error generating new address

### ISSUE THREAD

**Issue by LightBurdenOfficial** [algobasket/PeatioCryptoExchange#38]
I am getting the following error when trying to generate a new address:

> F, [2019-02-16T11:57:53.326545 #12211] FATAL -- :
> ActionView::MissingTemplate (Missing template private/deposits/satoshis/gen_address, private/deposits/base/gen_address, private/base/gen_address, application/gen_address with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :slim, :coffee]}. Searched in:
>   * "/home/root/peatio/app/views"
>   * "/home/root/peatio/vendor/bundle/ruby/2.3.0/gems/kaminari-0.15.1/app/views"
>   * "/home/root/peatio/vendor/bundle/ruby/2.3.0/gems/datagrid-1.0.5/app/views"
>   * "/home/root/peatio/vendor/bundle/ruby/2.3.0/gems/doorkeeper-1.4.1/app/views"
> ):
>   lib/middleware/security.rb:11:in `call'

**Comment by algobasket** [comment]
check whether bitcoind is running or not

**Comment by LightBurdenOfficial** [comment]
It is running perfectly, even though the address is generated when the user logs into the system, but when clicking the button to generate a new one, the platform returns the error.

> check whether bitcoind is running or not

**Comment by algobasket** [comment]
there must be some misconfiguration .Send me your vps access
