### ISSUE TITLE
Add New Coin

### ISSUE THREAD

**Issue by LightBurdenOfficial** [algobasket/PeatioCryptoExchange#41]
After adding the new currencies in the system, following the step by step provided in the documentation. What would be the command to enable them for users?
I have noticed that I have to resend the db: setup command, but all user accounts are deleted ...

What could be doing wrong?

Note: After the db: setup command, but currencies appear in the system normally.

**Comment by Apollo-IT** [comment]
Hi, @DigitalCoin1 How are you?
You look like you're finding an open source cryptocurrency exchange.
I can guide you.
Please contact me.
Regards.

Skype: live:apollo447722
Email: apollo447722@outlook.com

**Comment by pankaj9310** [comment]
@DigitalCoin1 
create file inside lib/tasks folder with name accounts.rake with below details
```
namespace :account do
  desc "add new account to old members according new currency"
  task :add_new_account_according_new_currency, [:ids] => :environment do
    Member.find_each do |m|
      less = Currency.codes - m.accounts.map(&:currency).map(&:to_sym)
      less.each do |code|
        m.accounts.create(currency: code, balance: 0, locked: 0)
      end
    end
  end
end
```
Run below command 
`bundle exec rake account:add_new_account_according_new_currency[ids] `
This will create accounts for new coins added

**Comment by LightBurdenOfficial** [comment]
Hello @pankaj9310 !
It worked here for me!
Now I have another situation that is not to receive deposits ...
I'm even using your version ...
Could you tell me where to look for a possible mistake?


Dashboard
![image](https://user-images.githubusercontent.com/32315718/56464777-49d75000-63c7-11e9-86ef-1987022b6af7.png)


SperoCoin.conf
![image](https://user-images.githubusercontent.com/32315718/56464785-62476a80-63c7-11e9-8a1a-8f873e7f7f6c.png)


SperoCoin Notification Daemon
![image](https://user-images.githubusercontent.com/32315718/56464790-725f4a00-63c7-11e9-91a0-be3ac1cac007.png)


RabbitMQ
![image](https://user-images.githubusercontent.com/32315718/56464801-94f16300-63c7-11e9-8470-175c3124704c.png)

Admin Dashboard
![image](https://user-images.githubusercontent.com/32315718/56464860-82c3f480-63c8-11e9-980b-2c58aeec5e56.png)


Wallet
![image](https://user-images.githubusercontent.com/32315718/56464859-6e7ff780-63c8-11e9-857a-9b61ad41af75.png)


Live Version:
https://exchange.sperocoin.org/

Fork:
https://github.com/DigitalCoin1/Spero-Exchange

**Comment by dagnyc** [comment]
@DigitalCoin1 I already have a script that adds users to new coins. My issue is that deposits “do” show up in the user’s account but confirmations always stay at 0 so the balance won’t go into user wallet. The issues is “confirmations” are not updating

**Comment by LightBurdenOfficial** [comment]
> I already have a script that adds users to new coins. My issue is that deposits “do” show up in the user’s account but confirmations always stay at 0 so the balance won’t go into user wallet. The issues is “confirmations” are not updating

As you can see in my last posts, the problem is the same as yours.
