### ISSUE TITLE
Deposits do not appear in user account

### ISSUE THREAD

**Issue by LightBurdenOfficial** [algobasket/PeatioCryptoExchange#42]
After making the deposit at the address that is automatically provided by the system, the amount is only available in the main admin panel, showing the total wallet balance, but the balance is not directed to the user.

**Comment by algobasket** [comment]
first you need to use the default wallet "" as the master wallet for the exchange
>bitcoin-cli getaddressesbylabel ""

**Comment by LightBurdenOfficial** [comment]
You see, it automatically creates addresses for deposits.
The addresses are named as "payment" within the wallets and these addresses are provided to the users.

When you send values ​​to addresses, the value is only available in the administrative panel, as you can see in the following image:

![image](https://user-images.githubusercontent.com/32315718/53600287-f6dfda00-3b87-11e9-9390-a4a8abc4e36c.png)

This is the wallet log:

![image](https://user-images.githubusercontent.com/32315718/53600465-63f36f80-3b88-11e9-9c95-da370d64ea84.png)

But this balance is not displayed in the user account.

Thanks for the attention, I decided to choose your project for editing, because I have seen that you are much more present than most of the developers for Peatio.

**Comment by dagnyc** [comment]
@digitalcoin1 did you get this resolved? You didn’t confirm that your default address is in your coin config in currencies.yml. But I will assume it is. That said I think you were looking for an answer about “what else could cause this problem?” Besides not having the default address in the coin config. There must be a next “most likely” cause of this issue. I believe that’s what we’re looking for here.
@algobasket what else could cause this kind of behavior? What would be the solution?

**Comment by LightBurdenOfficial** [comment]
@dagnyc Did you understand what I described above?
The address is generated on the panel, when a deposit is sent to the address, it arrives in the wallet and shows only in the ADMIN panel as in the image sent above.
However, this value is not directed to the user, that is, it is not available for use.
No information about the submitted transaction is created on the user panel.

**Comment by dagnyc** [comment]
@DigitalCoin1 Yes, I understood perfectly. I have exactly the same issue.

**Comment by LightBurdenOfficial** [comment]
The messages are even arriving directly by RabbitMQ.

![image](https://user-images.githubusercontent.com/32315718/54634063-25065a80-4a60-11e9-83a4-4f49a3a8d73a.png)
![image](https://user-images.githubusercontent.com/32315718/54634089-30598600-4a60-11e9-95f8-2abcf4fd9e75.png)
![image](https://user-images.githubusercontent.com/32315718/54634125-45ceb000-4a60-11e9-8fbb-e99bc81e2520.png)

**Comment by dagnyc** [comment]
@DigitalCoin1 I've made some progress. I can see the deposit in the deposit history in the user wallet but 0 confirmations. So the balance doesn't update. @algobasket can you give us some advice as to why the deposit shows up in the user wallet but always has 0 confirmations?

**Comment by dagnyc** [comment]
> 
> 
> @dagnyc Did you understand what I described above?
> The address is generated on the panel, when a deposit is sent to the address, it arrives in the wallet and shows only in the ADMIN panel as in the image sent above.
> However, this value is not directed to the user, that is, it is not available for use.
> No information about the submitted transaction is created on the user panel.

@DigitalCoin1 Make sure in your currencies.yml you have the coin name "key" in the walletnotify line. 
ex. walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

change from satoshi to the "key" name of your coin. Then restart both your coin daemon and all peatio daemons. Then the deposit will show up in the user wallet

**Comment by LightBurdenOfficial** [comment]
> > @dagnyc Did you understand what I described above?
> > The address is generated on the panel, when a deposit is sent to the address, it arrives in the wallet and shows only in the ADMIN panel as in the image sent above.
> > However, this value is not directed to the user, that is, it is not available for use.
> > No information about the submitted transaction is created on the user panel.
> 
> @DigitalCoin1 Make sure in your currencies.yml you have the coin name "key" in the walletnotify line.
> ex. walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'
> 
> change from satoshi to the "key" name of your coin. Then restart both your coin daemon and all peatio daemons. Then the deposit will show up in the user wallet


Hello!
Check it out in my last post. It has the image of the wallet notification.
![image](https://user-images.githubusercontent.com/32315718/54800396-66edf700-4c40-11e9-932f-4f082648fc2e.png)

**Comment by dagnyc** [comment]
@DigitalCoin1 did you ever get deposits to work correctly. And deposit confirmations?

**Comment by LightBurdenOfficial** [comment]
> @DigitalCoin1 did you ever get deposits to work correctly. And deposit confirmations?

Nothing yet....

**Comment by dagnyc** [comment]
I know rabbitmq is working. I have deposits in user history but status is “submitted”. 0 confirmations and never changes. How peatio checks confirmations?

**Comment by dagnyc** [comment]
@DigitalCoin1 I think I’m getting closer to figuring this out. It’s definitely an rpc related issue but I’m not sure which file has the code that needs to be fixed, yet. Doing some ruby troubleshooting. 
![09C0C387-3ABC-481C-867F-10A39942E84A](https://user-images.githubusercontent.com/18625900/56689700-aa0d1100-66a9-11e9-9404-d5600a92787f.jpeg)
 See the image

**Comment by dagnyc** [comment]
To understand what I’m doing look at the file ~/peatio/app/services/coin_rpc.rb
There is a variable or method ‘c’ that calls to c.rpc 
At that point it is supposed to look for the setting you put in currencies.yml for “family”. 
So in this case I have a coin that has Bitcoin codebase so the family is set to BTC.
Then that would take the BTC < self method and send the request for blockchain info via json. But it is failing. Not sure “where” it is failing but I’m looking.

**Comment by dagnyc** [comment]
![EEC27D05-8526-47FB-9922-E0A0AE1D1F89](https://user-images.githubusercontent.com/18625900/56690642-f1949c80-66ab-11e9-9a6c-bb4ce211d58d.png)

**Comment by LightBurdenOfficial** [comment]
@dagnyc see this:
https://github.com/algobasket/PeatioCryptoExchange/issues/41

**Comment by dagnyc** [comment]
@DigitalCoin1 I already have a script that adds users to new coins. My issue is that deposits “do” show up in the user’s account but confirmations always stay at 0 so the balance won’t go into user wallet. The issues is “confirmations” are not updating

**Comment by dagnyc** [comment]
@DigitalCoin1 go to Discord please

**Comment by wes45** [comment]
I am facing the same problem; deposits do show in the Admin panel, but do not show in the user account. Did you find the solution to this problem? Would be great if you are willing to share it, thanks!

**Comment by LightBurdenOfficial** [comment]
Unfortunately I still have no answer to this problem ...

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
