### ISSUE TITLE
Error Solvency

### ISSUE THREAD

**Issue by LightBurdenOfficial** [algobasket/PeatioCryptoExchange#45]
> I, [2019-02-26T14:06:28.695321 #19921]  INFO -- : Completed 500 Internal Server Error in 5983ms
> F, [2019-02-26T14:06:28.697473 #19921] FATAL -- : 
> ActionView::Template::Error (undefined method `sum' for nil:NilClass):
>     11:         span.title = t('.btc-assets-total')
>     12:         span.currency
>     13:           == t("currency.icon.btc")
>     14:           = @btc_proof.sum
>     15:       = render 'liability_data', account: @btc_account, proof: @btc_proof
>     16: 
>     17:     #brl-proof.tab-pane:        .trade-wrapper
>   app/views/private/assets/_liability_tabs.html.slim:14:in `_app_views_private_assets__liability_tabs_html_slim__1354508124934000459_47444682067040'
>   app/views/private/assets/_liability_proof.html.slim:10:in `_app_views_private_assets__liability_proof_html_slim__2601858994275372780_47444682541520'
>   app/views/private/assets/index.html.slim:21:in `block in _app_views_private_assets_index_html_slim___498693701765864209_47444684108620'
>   app/views/private/assets/index.html.slim:1:in `_app_views_private_assets_index_html_slim___498693701765864209_47444684108620'
>   lib/middleware/security.rb:11:in `call'

**Comment by algobasket** [comment]
Solvency module and its functions are deprecated and removed !

**Comment by LightBurdenOfficial** [comment]
Thanks!
