### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by dagnyc** [algobasket/PeatioCryptoExchange#47]
Still can't login to the admin area of the site. This is my 3rd time installing peatio and I've never been able to get to the admin area. It is unclear in the installation instruction how to properly access the admin site. It would be helpful to have something like the following in the instructions:
#############################################
How to login to admin area: http://yourdomain.com/admin
#############################################
what I'm looking for is the exact url. There has been reference to using port 3000 but yet again it is very vague and unclear

I have the site up and running. I completed the final steps as per the instructions
"bundle exec rake daemons:start"
"bundle exec rails server"
then
Visit http://localhost:3000

user: admin@peatio.dev
pass: Pass@word8

I can't understand why I can get to the main home page and sign in page but not the admin area? 

After running "bundle exec rails server" I get this:

deploy@TVSERVER:~/peatio$ bundle exec rails server
=> Booting WEBrick
=> Rails 4.0.12 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2019-03-03 06:08:22] INFO  WEBrick 1.3.1
[2019-03-03 06:08:22] INFO  ruby 2.2.2 (2015-04-13) [x86_64-linux]
[2019-03-03 06:08:22] INFO  WEBrick::HTTPServer#start: pid=3833 port=3000

my port 3000 is open in the firewall, the site is up and running. What am I doing wrong?
What is the correct url to go to after fully competing the install with a domain name instead of "localhost" or "ipaddress"?
Can https be causing and issue? does the port 3000 need to be in the site conf file in nginx? next to port 80?

**Comment by dagnyc** [comment]
I've seen screenshots of people logged into their admin panel and the url shows as http://domainname.com/admin. Also http://domainname.com:3000/admin
Which is the correct way?

**Comment by dagnyc** [comment]
<img width="922" alt="peatio admin panel in nav" src="https://user-images.githubusercontent.com/18625900/53692197-87214900-3d59-11e9-9d5a-b77b5de35576.PNG">
When I click on my account like in the above pic I get the dropdown menu and the option for admin panel. When I hover over the admin panel I can see the url at the bottom of my browser and it is "https://mydomain.com/admin"
So it seems the correct address "https://mydomain.com/admin" but when I go to it I get redirected back to my account page, not the admin panel. What would cause this behavior?

**Comment by dagnyc** [comment]
If someone can help me get this straightened out I will do a pull request with a new write up of how to access the admin panel for the first time after the initial installation.

**Comment by dagnyc** [comment]
@algobasket please help me figure this out. Many people are having this issue

**Comment by dagnyc** [comment]
Not sure why but this time after I did the 2FA on my admin account I was able to browse to the admin panel. I'll close this case as after a fresh install and 2FA I'm in. So if any has this issue just reinstall, get inn with your admin account and then do the 2FA first before any thing else. Then logout and log back in and from your account menu click on admin panel and you should be able to get in. @algobasket sorry for soo many questions.

**Comment by nnzo** [comment]
Hey @dagnyc!

I cannot seem to be able to login... I just get the wrong username/password.
Do you know what the correct default admin login is? Thanks!

**Comment by pankaj9310** [comment]
Hi all
For admin login you need to activate 2FA.
You can check admin username and password db/seeds.rb file

**Comment by nnzo** [comment]
Wow, thanks so much!

You are much more help than @algobasket That just demands money
