### ISSUE TITLE
rake db:setup error

### ISSUE THREAD

**Issue by bitbd83** [algobasket/PeatioCryptoExchange#50]
NoMethodError: undefined method `observers=' for ActiveRecord::Base:Class
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:110:in `block (3 levels) in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:109:in `each'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:109:in `block (2 levels) in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:108:in `block in <class:Railtie>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
/home/deploy/.rbenv/peatio/config/environment.rb:5:in `<top (required)>'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/home/deploy/.rbenv/peatio/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'

**Comment by bitbd83** [comment]
resolved!

**Comment by ghost** [comment]
> resolved!

same wrong :( 
how to resolve ?
