### ISSUE TITLE
Error when creating new address

### ISSUE THREAD

**Issue by dagnyc** [algobasket/PeatioCryptoExchange#51]
<img width="864" alt="deposit_issue" src="https://user-images.githubusercontent.com/18625900/54477903-ea43be80-47e2-11e9-921a-8251d72d64d4.PNG">
Hi, I get the following error when I try to create a new address:

"The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

I attached a pic. I have triple check my wallet settings and log file for hot wallet. No issues with rpc user/pass (checked with curl too). Just can't create a new address.
@algobasket What could cause this error?

**Comment by poseidon-j** [comment]
https://youtu.be/YP6o_R-Y_AQ

**Comment by dagnyc** [comment]
@bjay27 thanks. Going over all configurations again and especially server.en.yml I have resoled the issue
