### ISSUE TITLE
Correct Ruby version

### ISSUE THREAD

**Issue by dagnyc** [algobasket/PeatioCryptoExchange#54]
@algobasket why does this document say to use ruby-2.2.2 https://github.com/algobasket/PeatioCryptoExchange/blob/rebuild-peatio/doc/deploy-production-server.md

but

this document says to use ruby-2.3.0 https://github.com/algobasket/PeatioCryptoExchange/blob/rebuild-peatio/doc/setup-local-ubuntu.md

Which is the correct version to use?

**Comment by pankaj9310** [comment]
@dagnyc 
use this  ruby-2.3.0 https://github.com/algobasket/PeatioCryptoExchange/blob/rebuild-peatio/doc/setup-local-ubuntu.md
https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/
I think migrate to ruby -v > 2.3. Their is no point to use old version that is dead.

**Comment by algobasket** [comment]
bootstrap-sass 3.2.0.2
This version has been yanked, and it is not available for download directly or for other gems that may have depended on it.
https://rubygems.org/gems/bootstrap-sass/versions/3.2.0.2 
INSTEAD OF rbenv install -v 2.2.2/2.3.0/2.3.3
USE **rbenv install -v 2.5.3**

**Comment by dagnyc** [comment]
@algobasket @pankaj9310 thanks guys. I installed 2.5.3 but now once again issues with json -v 1.8.1 and it fails to install. Why is there always a problem with this? It's beyond frustrating. I changed the json version in Gemfile to 1.8.1 but it doesn't compile properly. I also tried just using gem install json which installs json -v 2.2.0 but apparently that version is not compatible. I've done all the "bundle update this" and "bundle update that" stuff. I've done every bundle known to man. Why can't these things just work without loosing hours of time

**Comment by dagnyc** [comment]
and bootstrap-sass-3.2.0.2 is nowhere to be found

**Comment by dagnyc** [comment]
I deleted the Gemfile and Gemfile.lock and then started with new ones from github. Bundle install was then successful and now I can start my daemons but the site doesn't work anymore. It just says "we're sorry but something went wrong". I think there is something wrong with figaro as I got warnings about it during the install about converting strings

**Comment by dagnyc** [comment]
Now I get this:

(StructuredWarnings::StandardWarning)** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
I, [2019-04-09T10:17:54.086851 #30290]  INFO -- : Writing /home/deploy/peatio/public/assets/font-awesome/fontawesome-webfont-d5b5636ebb2e124810436200086b74a60dff9e8a8be7f4a1088bf5d3458bc3c8.svg.gz
rake aborted!
Sprockets::FileNotFound: couldn't find file 'bootstrap-wysihtml5/b3' with type 'application/javascript'

and this:

Tasks: TOP => assets:precompile
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.

**Comment by dagnyc** [comment]
Ok so from what I can see, Figaro is working fine (but with a warning). All my daemons can stop/start with no problem. All rake commands work fine except for bundle exec rake assests:precompile

That's when I get the error about gzip not closing properly. Now that may have something to do with bootstrap-wysihtml5/b3 not being found. If I can get this resolved I think the site should be ok.. At the moment I still can't load the site in the browser. Just get the same error "we're sorry something went wrong"

**Comment by dagnyc** [comment]
I moved bootstrap-sass-3.2.0.2 from ruby 2.2.0 to ruby 2.5.0. Compiling gets a little further but now I have a different error:

Sass::SyntaxError: File to import not found or unreadable: bootstrap-wysihtml5/core-b3.

**Comment by dagnyc** [comment]
I found out that bootstrap-sass 3.2.0.2 and 3.2.0.3 were yanked due to a vulnerability introduced by a rouge github commit. In it's place version 3.2.0.4 was released but now doesn't have b3.js or core-b3.js
https://github.com/twbs/bootstrap-sass/issues/1195

how can we resolve this? @algobasket

**Comment by dagnyc** [comment]
So I tried to revert back to 2.2.2 but now it's all messed up and can't complete the bundle install. Too many gem compatibility issues. The peatio installation is completely torched. I had peatio working fine with 2.2.2. Now it's all gone. All that work and hours, days, months of my life gone. Thanks

**Comment by blacklevel7** [comment]
Hi @dagnyc , did you find a solution?

**Comment by algobasket** [comment]
rbenv install -v 2.2.1 | rbenv install -v 2.2.2 | rbenv install -v 2.2.7
gem install bundler -v 1.9.2
and bootstrap-sass 3.2.0.4
Enjoy !
