### ISSUE TITLE
bootstrap sass 3.4.1 

### ISSUE THREAD

**Issue by bitbd83** [algobasket/PeatioCryptoExchange#55]
bootstrap 3.4.1 need 2 dependency 
gem need 2 dependency  autoprefixer-rails >= 5.2.1
 sassc >= 2.0.0
which are not included in Gemfile or Gemfile.lock

**Comment by dagnyc** [comment]
@bitbd83 are you using ruby 2.5.3?

**Comment by algobasket** [comment]
@bitbd83 
rbenv install -v 2.2.1 | rbenv install -v 2.2.2 | rbenv install -v 2.2.7
gem install bundler -v 1.9.2
and bootstrap-sass 3.2.0.4
Enjoy !
