### ISSUE TITLE
bundle install failed

### ISSUE THREAD

**Issue by casterminator** [algobasket/PeatioCryptoExchange#56]
following the instructions for UBUNTU - received the error below:

-----------------------------------------------------

The git source `git://github.com/InfraexDev/unread.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/InfraexDev/mina-slack.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/InfraexDev/unread.git
Fetching git://github.com/InfraexDev/mina-slack.git
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    figaro was resolved to 0.7.0, which depends on
      bundler (~> 1.0)

    rails (~> 4.0.12) was resolved to 4.0.12, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails (~> 4.0.12)', in any of the sources.

**Comment by dagnyc** [comment]
Use bundler 1.9.2

**Comment by casterminator** [comment]
got another error after using Bundler 1.9.2

----------------------------------------------------------------------------

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/home/deploy/.rbenv/versions/2.3.0/bin/ruby -r ./siteconf20190408-23329-1ja5ne1.rb extconf.rb
creating Makefile

current directory: /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
Makefile:238: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/deploy/peatio/vendor/bundle/ruby/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /home/deploy/peatio/vendor/bundle/ruby/2.3.0/extensions/x86_64-linux/2.3.0-static/json-1.8.1/gem_make.out
An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

**Comment by algobasket** [comment]
> gem install json -v '1.8.1'

go to Gemfile and update the version then
bundle install ......etc

**Comment by algobasket** [comment]
@casterminator 
rbenv install -v 2.2.1 | rbenv install -v 2.2.2 | rbenv install -v 2.2.7
gem install bundler -v 1.9.2
and bootstrap-sass 3.2.0.4
Enjoy !

**Comment by violetdroidxz** [comment]
HI algobasket,
when I ran this cmd : 
bundle install --without development test --path vendor/bundle

^^^this is git://xxxx protocol and this protocol always throwing error,I want to use https:// instead of git:// ???

**Comment by algobasket** [comment]
> HI algobasket, when I ran this cmd : bundle install --without development test --path vendor/bundle
> 
> ^^^this is git://xxxx protocol and this protocol always throwing error,I want to use https:// instead of git:// ???

Clone it using https://
