### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by blacklevel7** [algobasket/PeatioCryptoExchange#59]
Dear @algobasket ,
I have installed peatio in VM (production mode), but my index page : "We're sorry, but something went wrong.".
What could be the reason? :(
Almost all log output files have error:s/warnings like this:

----
`/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 60 was converted to "60". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 8080 was converted to "8080". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 65910 was converted to "65910". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 443 was converted to "443". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/home/deploy/peatio/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)`
Terminating threads ..
Stopped.

**Comment by algobasket** [comment]
your ruby version 2.5.0 doesn't find some of the gem dependencies when bundle install .... So , you need to install it manually
instead of 2.5.0 you can use 2.2.7 
rbenv install -v 2.2.7 (don't use 2.2.1 is very old) 
and gem install bundler -v 1.9.2
also change Gemfile bootstrap-sass to 2.3.0.4

**Comment by algobasket** [comment]
I updated the code 
Or you can also use from here
https://bitbucket.org/AlgoBasketTeam2018/peatio2.0/src/master/
