### ISSUE TITLE
exchange setup

### ISSUE THREAD

**Issue by cryptohood** [algobasket/PeatioCryptoExchange#60]
hi has anyone got a correct updated installation guide with correct gem files etc compatible with latest updates.. i have been trying to install for several days and non of this is correct, its all over the place, it isnt straight forward as such as there so many out dated and errors and files cant be found.

scroll through issues keep uptodate with latest, solve a problem then theres another issue.

can anyone help and direct with this backwords guide

**Comment by algobasket** [comment]
#61

**Comment by blacklevel7** [comment]
@cryptohood 
Latest setup works good.
One thing:
instead of "gem install bundler" run 
gem install bundler -v 1.9.2

and everything must done withouth any errors

**Comment by algobasket** [comment]
Yes  gem install bundler -v 1.9.2 :+1:

**Comment by PHTTOKENX** [comment]
Thanks guys will have another go now. Much appreciated

**Comment by cryptohood** [comment]
thank you im going to try install now

**Comment by cryptohood** [comment]
yes lads everything going smooth no errors, great work and thank you.

i just have 1 final problem stopping me from launching live on my server.

when i am at the last stages of config files i follow the steps and enter my pusher credentials etc but i dont think it seems to save it, i hold ctrl X then asks to save etc and i do and then to create new file it wont let me say no so i just say yes to back out onto root 

i get these following errors at the bottom when i do bundle exec rake db:setup.

please can i have help on the correct way and keys to usde to save the config files. thank you once again


/root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:609:in `block (2 levels) in <class:Engine>'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
-bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in: No such file or directory
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `each'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `block in <class:Engine>'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
-bash: class:Engine: No such file or directory
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `each'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
-bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in: No such file or directory
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `tsort_each_child'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
-bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in: No such file or directory
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
> /root/peatio/config/environment.rb:5:in `<top (required)>'
-bash: syntax error near unexpected token `('
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
-bash: command substitution: line 1: unexpected EOF while looking for matching `''
-bash: command substitution: line 3: syntax error: unexpected end of file
-bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in: No such file or directory
root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require'
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
-bash: !': event not found
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
> Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
> (See full trace by running task with --trace)

**Comment by algobasket** [comment]
> yes lads everything going smooth no errors, great work and thank you.
> 
> i just have 1 final problem stopping me from launching live on my server.
> 
> when i am at the last stages of config files i follow the steps and enter my pusher credentials etc but i dont think it seems to save it, i hold ctrl X then asks to save etc and i do and then to create new file it wont let me say no so i just say yes to back out onto root
> 
> i get these following errors at the bottom when i do bundle exec rake db:setup.
> 
> please can i have help on the correct way and keys to usde to save the config files. thank you once again
> 
> /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency'
> 
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:223:in `load' /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:609:in `block (2 levels) in class:Engine'
> > -bash: command substitution: line 1: unexpected EOF while looking for matching `'' -bash: command substitution: line 3: syntax error: unexpected end of file -bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in: No such file or directory root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `each'
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/engine.rb:608:in `block in <class:Engine>' /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `instance_exec'
> > -bash: command substitution: line 1: unexpected EOF while looking for matching `'' -bash: command substitution: line 3: syntax error: unexpected end of file -bash: class:Engine: No such file or directory root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in `run'
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:55:in `block in run_initializers' /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `each'
> > -bash: command substitution: line 1: unexpected EOF while looking for matching `'' -bash: command substitution: line 3: syntax error: unexpected end of file -bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:30:in: No such file or directory root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in `tsort_each_child'
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:54:in `run_initializers' /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:215:in `initialize!'
> > -bash: command substitution: line 1: unexpected EOF while looking for matching `'' -bash: command substitution: line 3: syntax error: unexpected end of file -bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/initializable.rb:44:in: No such file or directory root@dex:~/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/railtie/configurable.rb:30:in `method_missing'
> > /root/peatio/config/environment.rb:5:in `<top (required)>' -bash: syntax error near unexpected token `('
> > root@dex:/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require' /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `block in require'
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:214:in `load_dependency' -bash: command substitution: line 1: unexpected EOF while looking for matching `''
> > -bash: command substitution: line 3: syntax error: unexpected end of file
> > -bash: /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in: No such file or directory
> > root@dex:/peatio# /root/peatio/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/dependencies.rb:229:in `require' /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:189:in `require_environment!'
> > -bash: !': event not found
> > /root/peatio/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:260:in `block in run_tasks_blocks'
> > Tasks: TOP => db:setup => db:schema:load_if_ruby => environment
> > (See full trace by running task with --trace)

LOL ..... 2.2.0 is too old
Use  2.2.1 OR (Easy)
        2.2.2  OR (Easy)
        2.2.7 OR (Easy)
        2.5.3 (Manually need to update specific Gem Packages)

**Comment by cryptohood** [comment]
i folowed the updated guides.. :-( 

whats the best route and commands for me to do please? i am new with scripts, trying to learn for several weeks very frustrating lol or if you have telegram by any chance would love direct instant help on the lasts niggles.

**Comment by algobasket** [comment]
> i folowed the updated guides.. :-(
> 
> whats the best route and commands for me to do please? i am new with scripts, trying to learn for several weeks very frustrating lol or if you have telegram by any chance would love direct instant help on the lasts niggles.

If Bundle install successful then Check Pusher Credentials 
This command "bundle exec rake db:setup" will succesful if Pusher Credentials are correct and Config/database.yml info correct .

**Comment by cryptohood** [comment]
i think its pusher settings etc, i do enter corretly but i dont think im saving it or correctly saving it. im on windows laptop how do i save it with the correct keys, ive been using Ctrl and Alt pressing all the menu keys and bashing my keyboard lool.


====================== WARNING ======================
  please check below config in config/application.yml

  PUSHER_APP
  PUSHER_KEY
  PUSHER_SECRET
=====================================================


i assume i havnt saved them

**Comment by blacklevel7** [comment]
Uncomment # demo pusher values and comment uout PUSHER_APP
PUSHER_KEY
PUSHER_SECRET

for testing

**Comment by cryptohood** [comment]
not with you mate not quite clear with what you mean im afraid. kind of lost as it is now lol

im still trying to save the edited config files but never saves it correctly, i press ctrl x then save then overwrite but no save has happened.

**Comment by algobasket** [comment]
> not with you mate not quite clear with what you mean im afraid. kind of lost as it is now lol
> 
> im still trying to save the edited config files but never saves it correctly, i press ctrl x then save then overwrite but no save has happened.

Instead of Vim use Nano
sudo nano [PATH]
Ctrl + O -> Save
Enter
Ctrl + x -> Close
(I USE LINUX BTW)

**Comment by cryptohood** [comment]
birllant thank you so much i followed your steps then re opened it to see it saved.. wicked thank you. i will now go through the config files again. ill update you if i succeed

**Comment by cryptohood** [comment]
it went all ok with no errors but cannot view the exchange via my IP on digital ocean that i put the same IP in one the config files i did which was requested and followed the video. 

guess ill try again in a hour

**Comment by cryptohood** [comment]
everything installed with no errors thankfully but when i go bundle exec rake assets:precompile
nothing happens, but in your video its compiling files, i refresh my server ip which is on digital ocean but nothing loads but the Welcome to nginx! i keep refreshing but nothing, i entered all the following correct in config files also saved correctly, adding my server ip in the database file or domain as stated but still nothing. any ideas?

**Comment by cryptohood** [comment]
whats best server for peatio?

i install successfully but cannot get passed welcome to nginx page? im using digital ocean

**Comment by dagnyc** [comment]
@cryptohood check your passenger path in nginx conf file

**Comment by cryptohood** [comment]
> @cryptohood check your passenger path in nginx conf file

i did so just now reinstalled and checked all, still wont load peatio. must be something wrong ive redone this 20+ times, ive deployed many others successfully but not this one

**Comment by cryptohood** [comment]
would anyone like to install it for me on digital ocean to find out if its me or the server providers.

**Comment by LightBurdenOfficial** [comment]
> would anyone like to install it for me on digital ocean to find out if its me or the server providers.

If you want I'll take a look at you.
Call me on the Telegram: @sperocoin


Remembering that I will only assist you in putting the system online, all the configuration of your coins should be made by you, including for your safety.

**Comment by cryptohood** [comment]
> > would anyone like to install it for me on digital ocean to find out if its me or the server providers.
> 
> If you want I'll take a look at you.
> Call me on the Telegram: @sperocoin
> 
> Remembering that I will only assist you in putting the system online, all the configuration of your coins should be made by you, including for your safety.

top man  you are thank you so much, will shout you on telegram now.

**Comment by cryptohood** [comment]
id like to give credit too @DigitalCoin1 for giving up his time to help me. very much appreciated help is hard to come by in crypto.

big up @algobasket  too great work with your project
