### ISSUE TITLE
peatio editing/custom

### ISSUE THREAD

**Issue by cryptohood** [algobasket/PeatioCryptoExchange#63]
hi all, finally i have the exchange up and running, i have gone through the files via my ftp client to check what files to edit but there are soooooo many im getting lost etc, sorry for my noob educated side.

i am able to edit basically but i need some help on the right direction to the correct folders so i can edit the home page and change the peatio logo with my logo on the exchange etc. any direction would be amazing.

thanks in advance

**Comment by pankaj9310** [comment]
@cryptohood 
app->views->welcome
Do required changes for home page

**Comment by algobasket** [comment]
![Screenshot from 2019-04-20 23-10-57](https://user-images.githubusercontent.com/8275673/56460515-9ae44580-63c1-11e9-8571-86d05715cd92.png)
![Screenshot from 2019-04-20 23-12-00](https://user-images.githubusercontent.com/8275673/56460527-c1a27c00-63c1-11e9-9d32-0032db388365.png)
![Screenshot from 2019-04-20 23-12-49](https://user-images.githubusercontent.com/8275673/56460538-e3036800-63c1-11e9-9f44-cea3435fd89b.png)
![Screenshot from 2019-04-20 23-14-32](https://user-images.githubusercontent.com/8275673/56460560-1940e780-63c2-11e9-815e-4d7c44a9adb9.png)

**Comment by cryptohood** [comment]
thanks so much guys.
