### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by wes45** [algobasket/PeatioCryptoExchange#66]
Hopefully someone could help by pointing into the right direction of a solution;
on frontend page funds#/deposits/ the translations for the coins show errors like
[missing "en.funds.deposit" translation]
[missing "en.funds.withdraw" translation]
[missing "en.funds.deposit_btc.title" translation]
[missing "en.funds.deposit_coin.open-wallet" translation]
I triple-checked the yaml formatting, recompiled, again and again but I just can't get it fixed. 
Guess I am being (very) stupid, could someone please advice? Thx!

**Comment by altcoin-services** [comment]
i had same problem with persian

**Comment by pankaj9310** [comment]
Have you added new coin?
if Yes then Add coin details on server.en.yml file

**Comment by m4hdi1995** [comment]
@pankaj9310 i did , it's all ok on english translation it shows correctly , i copied exact same yaml file and just added the translation , but it doesn't show it.

**Comment by pankaj9310** [comment]
Run below command
`rake tmp:clear`
after that recompile the assets

**Comment by wes45** [comment]
Hi pankaj,  thank you very much for advicing, you are the greatest.
The rake tmp:clear command and recompile did the trick, it is all OK now.
Cheers to you!
