### ISSUE TITLE
change markets drop down to base market instead of quote market

### ISSUE THREAD

**Issue by altcoin-services** [algobasket/PeatioCryptoExchange#67]
hello,
i wanted to change markets drop down to base market instead of quote market,
i tried changing : 
app/controllers/private/markets_controller.rb line 15 from:
@market_groups = @markets.map(&:quote_unit).uniq 
to:
@market_groups = @markets.map(&:base_unit).uniq
other markets than market pairs disappeared, but when i click on for example btc market it doesn't show anything,
i also changed : 
&.eth { tr.quote-eth { display: block; } }
to : 
&.eth { tr.base-eth { display: block; } }
on:
app/assets/stylesheets/market.dss.scss 
it didn't worked either,
any help? thanks.

**Comment by altcoin-services** [comment]
Actually I wanted the markets drop down to show only market pairs not all coins which I added to exchange.

**Comment by pankaj9310** [comment]
Add flag on markets.yml file and use that

**Comment by m4hdi1995** [comment]
@pankaj9310 thanks for your answer , what do you mean ? it's one of coins on my markets.yml :
- id: btceth
  code: 1
  name: BTC/ETH
  base_unit: btc
  quote_unit: eth
  #price_group_fixed: 1 # aggregate price levels in orderbook
  bid: {fee: 0.1, currency: btc, fixed: 8}
  ask: {fee: 0.1, currency: eth, fixed: 8}
  sort_order: 1
  #visible: false     # default to true

**Comment by pankaj9310** [comment]
#visible: false # default to true  
un comment this line and set visible:false

**Comment by altcoin-services** [comment]
@pankaj9310 it says "We're sorry, but something went wrong."
after uncommenting #visible: false

**Comment by altcoin-services** [comment]
managed to make it work by switching base with quote on markets.yml
