### ISSUE TITLE
Added altcoin but deposit address not generated

### ISSUE THREAD

**Issue by wes45** [algobasket/PeatioCryptoExchange#68]
Could someone please advice;I  added an altcoin but the funds#/deposits/ page for the coin is empty. There is no text and no deposit address shown. The production.log returns this:

INFO -- : Started POST "/funds/gen_address"  at 2019-05-01 14:48:35 +0200
INFO -- : Processing by Private::FundsController#gen_address as */*
INFO -- : Completed 500 Internal Server Error in 15ms
FATAL -- :  NoMethodError (undefined method `coin?' for nil:NilClass):
  app/controllers/private/funds_controller.rb:24:in `block in gen_address'
  app/controllers/private/funds_controller.rb:23:in `gen_address'
  lib/middleware/security.rb:11:in `call'

and tail -f log/peatio:amqp:deposit_coin.output returns this:

I, [2019-05-01T15:37:46.983577 #29942]  INFO -- : Received: {"payment_address_id":3,"currency":"sucr","locale":"en"}
F, [2019-05-01T15:37:46.985749 #29942] FATAL -- : end of file reached (EOFError)
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `catch'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1384:in `request'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:853:in `start'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in `request'
/home/user01/peatio/app/services/coin_rpc.rb:44:in `http_post_request'
/home/user01/peatio/app/services/coin_rpc.rb:32:in `handle'
/home/user01/peatio/app/services/coin_rpc.rb:23:in `method_missing'
/home/user01/peatio/app/models/worker/deposit_coin_address.rb:14:in `process'
/home/user01/peatio/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/user01/peatio/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2019-05-01T15:37:46.985884 #29942] FATAL -- : /home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `read_nonblock'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:153:in `rbuf_fill'
/home/user01/.rbenv/versions/2.2.7/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'

**Comment by altcoin-services** [comment]
@wes45 hello, im getting 
NoMethodError (undefined method `coin?' for nil:NilClass):
error too , did you solved it?

**Comment by wes45** [comment]
hi there,
No, unfortunately could not get it to work. I stopped working with peatio, too buggy and it takes too much time to find solutions. good luck with your project

**Comment by algobasket** [comment]
@wes45
On new peatio v3 you can add any altcoins or tokens and more , its under development and will release soon.
