### ISSUE TITLE
How to change account requirements for trading?

### ISSUE THREAD

**Issue by wes45** [algobasket/PeatioCryptoExchange#70]
Could someone please advice what file(s) to edit to change the requirements for tradingon the Profile page , /settings  ? In example, I would like to disable and remove the Phone number and API tokens sections, and have accounts active for trading after email confirmation and 2FA enabled. If that is possible, what files to edit?

**Comment by pankaj9310** [comment]
Simple solution
2FA work either google authentication is enabled or Mobile number verified 
so if you remove mobile number then it should work.
simply remove links from settings view page and disable that link from routes

**Comment by altcoin-services** [comment]
from app/views/private/settings/index.html.slim remove phone number and api tokens ,
if you want to remove users verification too , you can but you need to change : app/models/id_document.rb  and spec/models/id_document_spec.rb  from unverified to verified too.

**Comment by wes45** [comment]
Thank you pankaj9310 and altcoin-services for helping out, that is really great!
