### ISSUE TITLE
change template

### ISSUE THREAD

**Issue by altcoin-services** [algobasket/PeatioCryptoExchange#71]
hello, 
i wanted to change default welcome template 
i tried to put my html template with all css files on app/views/welcome/
and i removed index.html.slim,
it didn't worked , thanks.

**Comment by pankaj9310** [comment]
What problem you are facing. If you are running on production then drecompile assets

**Comment by altcoin-services** [comment]
@pankaj9310 , I want to change the welcome template , when I open my server there is a peatio logo with a ribbon on top right and a few buttons , I want to change template with my own HTML template.

**Comment by wes45** [comment]
Hi altcoin-services,
in /peatio/app/assets/images you can change the logo
in /peatio/app/assets/stylesheets/features/_welcome.css.scss there is ribbon info,
for the ribbon text check out the lang files
hope that helps, cheers

**Comment by blacklevel7** [comment]
> i wanted to change default welcome template
> i tried to put my html template with all css files on app/views/welcome/
> and i removed index.html.slim,
> it didn't worked , thanks.

You need to rebuild assets after each change,,

bundle exec rake assets:clean
bundle exec rake assets:clobber
bundle exec rake tmp:clear
bundle exec rake assets:precompile
sudo service nginx restart

**Comment by altcoin-services** [comment]
@blacklevel7 it's been fixed , I had to copy my template on public folder.
