### ISSUE TITLE
Follow Conventional Commits for git commits

### ISSUE THREAD

**Issue by iadj** [algobasket/PeatioCryptoExchange#73]
Most commits of this repo are undescriptive (only says `changes`):

![image](https://user-images.githubusercontent.com/8861459/57371130-3f240580-7192-11e9-87a8-a1621202403c.png)

It's hard to see what's being updated this way. Could you please follow the [Conventional Commits standard](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary) to make development easier to follow (and contribute to)? For example, instead of `changes` or `bug fixed`:

* `chore(admin): fix admin dashboard css` 
* `feat(wallet): add support for erc20`
* `feat(infra): add docker yaml config`
* `feat(lang): add russian language`

**Comment by algobasket** [comment]
Okay, that's auto-commit via Cron. For specific changes, we only do manual commit from the terminal .
