### ISSUE TITLE
Monero and CN

### ISSUE THREAD

**Issue by altcoin-services** [algobasket/PeatioCryptoExchange#74]
Hello,
i found this commit :
https://github.com/InfraexDev/peatio/pull/106/files
i'm trying to add monero and other cryptonote coins ,
it didn't worked , does anybody done it successfully?

**Comment by algobasket** [comment]
Just simply adding monero/XRP won't work you need to do some changes within the rails codes. You can add any coins/tokens if you know how to code for it .

**Comment by altcoin-services** [comment]
@algobasket i know that , take a look at the link , i have changed coin rpc i was hoping somebody else had any clue on this

**Comment by algobasket** [comment]
making rpc connection on currencies.yml , Markets.yml,Deposit.yml,Withdraw.yml is just 1% work not any backend coding

**Comment by altcoin-services** [comment]
@algobasket i need to add rpc commands to app/services/coin_rpc.rb too right? like this : https://github.com/InfraexDev/peatio/pull/106/files what else?

**Comment by altcoin-services** [comment]
i already added coins based on bitcoin and they works

**Comment by altcoin-services** [comment]
there is something wrong with my cryptonote rpc implementation

**Comment by algobasket** [comment]
Ask him skype ( live:etherlaunch) he will help you

**Comment by altcoin-services** [comment]
@algobasket thanks but isn't there any telegram account?

**Comment by algobasket** [comment]
https://t.me/PeatioCryptoExchange

**Comment by altcoin-services** [comment]
@algobasket it's a channel , I will contact using Skype , thanks.

**Comment by blacklevel7** [comment]
Hi @altcoin-services,
can you share information how to setup CN coins If you succeeded? :)

**Comment by altcoin-services** [comment]
@blacklevel7 hey , yes I will but Skype guy didn't helped , I've opened a bounty.
