### ISSUE TITLE
How to display market status on the main page ?  

### ISSUE THREAD

**Issue by AnthonyRex** [algobasket/PeatioCryptoExchange#77]
any idea of how to get this script to display the markets status like this here ? any help will be appreciated.
![Screenshot (1)](https://user-images.githubusercontent.com/43102294/58365164-bf689b80-7ef2-11e9-8daa-2e141d18fe9d.png)

**Comment by algobasket** [comment]
Use Peatio API Or TradingView API Or TradingView Widgets Or Binance API
Example : http://45.32.148.230/
