### ISSUE TITLE
Change Markets Page Title

### ISSUE THREAD

**Issue by devzone777** [algobasket/PeatioCryptoExchange#78]
Hello,

How to change Markets page title in tab? To change from Peatio to other name? See image please
![remove_peatio_name_from_page_title](https://user-images.githubusercontent.com/50347092/58436738-e1018880-8094-11e9-89fb-79eeb91bfb79.PNG)

**Comment by algobasket** [comment]
Go to config/locales/ and do changes to client.en.yml and server.en.yml files
