### ISSUE TITLE
Admin Panel & User Dashboard

### ISSUE THREAD

**Issue by JefersonMartin** [algobasket/PeatioCryptoExchange#79]
Hello all,

How can I access the Admin Panel and User Dasboard ? I can only access the Trading UI and User Profile....

Thanks a lot.

**Comment by algobasket** [comment]
You can access here - 
![Screenshot from 2019-08-13 11 01 16](https://user-images.githubusercontent.com/8275673/62917416-cef0d580-bdb9-11e9-8fe7-5eb19d10fb45.png)
![Screenshot from 2019-08-13 11-03-59](https://user-images.githubusercontent.com/8275673/62917494-1bd4ac00-bdba-11e9-8b85-1f9bd36ff6c0.png)

**Comment by ultra-pool** [comment]
@algobasket When I click on admin all it does is take me back to the settings page. It doesnt show that 2nd screenshot you have above. Plus it doesnt have the dashboard menu on the left side even though it shows the admin under my email.
