### ISSUE TITLE
Google Authenticator Fails

### ISSUE THREAD

**Issue by devzone777** [algobasket/PeatioCryptoExchange#80]
Hi @algobasket 

I just did a new installation but now Google 2FA keeps failing. The error message is: "Password for authentication is incorrect, please re-enter."

I thought the problem was the time/date setting on the server but I set both the server and the application.yml timezone to "UTC" but it still doesn't work. Any idea what could be causing the failure?

**Comment by algobasket** [comment]
![Screenshot from 2019-08-17 22 21 18](https://user-images.githubusercontent.com/8275673/63214975-60a36e80-c13d-11e9-8793-0c784a83724a.png)
Sync clock with google

**Comment by devzone777** [comment]
@algobasket is there a way to sync clock with a CLI command?

**Comment by algobasket** [comment]
get Google 2FA Mobile App  OR  Google 2FA Chrome Extension.

**Comment by GENUNCOIN** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
