### ISSUE TITLE
Updating old account with new currencies

### ISSUE THREAD

**Issue by joenilan** [algobasket/PeatioCryptoExchange#9]
I've been all over regarding this. When you add a new currency, the older accounts before the newest coin was added do not have new coin wallets.

You can manually go into the accounts table and add them in by editing the number under the currency column or using something like this to do it automatically? which i couldn't get to work.

[https://github.com/Brexchange/Brexchange/blob/stable/lib/tasks/account.rake](https://github.com/Brexchange/Brexchange/blob/stable/lib/tasks/account.rake)
or
[https://github.com/rubykube/peatio/blob/master/lib/tasks/accounts.rake](https://github.com/rubykube/peatio/blob/master/lib/tasks/accounts.rake)

`NoMethodError: undefined method `to_sym' for nil:NilClass
/home/deploy/peatio/lib/tasks/account_update.rake:5:in `map'`

Adding them in manually is horrible but it does the job, but it leaves a problem under the admin dashboard when you view a member of whose wallet you added. 

**UPDATE: I've fixed this part below, it was a dumb error on my end not adding it to the payment_address table, the update script problem remains**
`I, [2018-10-21T04:51:41.145697 #18051]  INFO -- : Started GET "/admin/members/4" for 108.162.219.74 at 2018-10-21 04:51:41 +0000
I, [2018-10-21T04:51:41.188945 #18051]  INFO -- : Processing by Admin::MembersController#show as HTML
I, [2018-10-21T04:51:41.188999 #18051]  INFO -- :   Parameters: {"id"=>"4"}
I, [2018-10-21T04:51:41.257062 #18051]  INFO -- :   Rendered shared/admin/_member.html.slim (23.9ms)
I, [2018-10-21T04:51:41.266877 #18051]  INFO -- :   Rendered shared/admin/_account.html.slim (7.2ms)
I, [2018-10-21T04:51:41.268388 #18051]  INFO -- :   Rendered shared/admin/_account.html.slim (1.4ms)
I, [2018-10-21T04:51:41.269478 #18051]  INFO -- :   Rendered shared/admin/_account.html.slim (1.0ms)
I, [2018-10-21T04:51:41.270561 #18051]  INFO -- :   Rendered shared/admin/_account.html.slim (1.0ms)
I, [2018-10-21T04:51:41.271382 #18051]  INFO -- :   Rendered shared/admin/_account.html.slim (0.8ms)
I, [2018-10-21T04:51:41.271438 #18051]  INFO -- :   Rendered shared/admin/_member_accounts.html.slim (14.0ms)
I, [2018-10-21T04:51:41.271487 #18051]  INFO -- :   Rendered admin/members/show.html.slim within layouts/admin (48.5ms)
I, [2018-10-21T04:51:41.271571 #18051]  INFO -- : Completed 500 Internal Server Error in 83ms
F, [2018-10-21T04:51:41.272374 #18051] FATAL -- : 
ActionView::Template::Error (undefined method `coin?' for nil:NilClass):
     8:       = item_for account, :amount
     9:       = item_for account, :locked
    10:       = item_for account, :balance
    11:       - if account.currency_obj.coin?
    12:         = item_for t('.payment_address') do
    13:           = account.payment_address.address
  app/views/shared/admin/_account.html.slim:11:in `_app_views_shared_admin__account_html_slim___271691715853936049_47242019128580'
  app/views/shared/admin/_member_accounts.html.slim:2:in `block in _app_views_shared_admin__member_accounts_html_slim__1164927640701448652_47242019342120'
  app/views/shared/admin/_member_accounts.html.slim:1:in `_app_views_shared_admin__member_accounts_html_slim__1164927640701448652_47242019342120'
  app/views/admin/members/show.html.slim:5:in `_app_views_admin_members_show_html_slim___1733331812087846287_47242024543200'
  lib/middleware/security.rb:11:in `call'`

is there a specific way you guys do this? any help much appreciated.

**Comment by legends420** [comment]
i created a script that grabbed all users and added the new coin information. im guessing you can do that same

**Comment by joenilan** [comment]
i've fixed 

> 
> 
> i created a script that grabbed all users and added the new coin information. im guessing you can do that same

thats what these are,
https://github.com/Brexchange/Brexchange/blob/stable/lib/tasks/account.rake
or
https://github.com/rubykube/peatio/blob/master/lib/tasks/accounts.rake

but i get the above error. i'm not knowledgeable enough to understand it. was just hoping someone had something similar they could point me in the right direction.

**Comment by joenilan** [comment]
fixed, didn't realize last error fixed caused this to fix.

closed
